export const WORKOUT_TEST_IDS = {
	page: 'workout-page',
	loading: 'workout-loading',
	header: 'workout-header',
	date: 'workout-date',
	heroCounter: 'hero-counter',
	totalReps: 'total-reps',
	progressBarFill: 'progress-bar-fill',
	repsLeft: 'reps-left',
	goalReached: 'goal-reached',
	goalDisplayBtn: 'goal-display-btn',
	goalInput: 'goal-input',
	goalSetBtn: 'goal-set-btn',
	quickAddButtons: 'quick-add-buttons',
	quickAddBtn: (reps: number) => `quick-add-${reps}`,
	setsLogEmpty: 'sets-log-empty',
	setsLog: 'sets-log',
	setsCount: 'sets-count',
	resetDayTrigger: 'reset-day-trigger',
	setRow: 'set-row',
	setReps: 'set-reps',
	setTime: 'set-time',
	deleteSetTrigger: 'delete-set-trigger',
	progressChart: 'progress-chart',
	chartMonthLabel: 'chart-month-label',
	prevMonthBtn: 'prev-month-btn',
	nextMonthBtn: 'next-month-btn',
	chartLoading: 'chart-loading',
} as const
