/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TestErrorRouteImport } from './routes/test/error'
import { Route as DashboardWorkoutRouteImport } from './routes/dashboard/workout'
import { Route as DashboardTimeTrackerRouteImport } from './routes/dashboard/time-tracker'
import { Route as DashboardSiteBlockingRouteImport } from './routes/dashboard/site-blocking'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test/error',
  path: '/test/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkoutRoute = DashboardWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimeTrackerRoute = DashboardTimeTrackerRouteImport.update({
  id: '/time-tracker',
  path: '/time-tracker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiteBlockingRoute = DashboardSiteBlockingRouteImport.update({
  id: '/site-blocking',
  path: '/site-blocking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site-blocking': typeof DashboardSiteBlockingRoute
  '/dashboard/time-tracker': typeof DashboardTimeTrackerRoute
  '/dashboard/workout': typeof DashboardWorkoutRoute
  '/test/error': typeof TestErrorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site-blocking': typeof DashboardSiteBlockingRoute
  '/dashboard/time-tracker': typeof DashboardTimeTrackerRoute
  '/dashboard/workout': typeof DashboardWorkoutRoute
  '/test/error': typeof TestErrorRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/site-blocking': typeof DashboardSiteBlockingRoute
  '/dashboard/time-tracker': typeof DashboardTimeTrackerRoute
  '/dashboard/workout': typeof DashboardWorkoutRoute
  '/test/error': typeof TestErrorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/settings'
    | '/dashboard/site-blocking'
    | '/dashboard/time-tracker'
    | '/dashboard/workout'
    | '/test/error'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/settings'
    | '/dashboard/site-blocking'
    | '/dashboard/time-tracker'
    | '/dashboard/workout'
    | '/test/error'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/settings'
    | '/dashboard/site-blocking'
    | '/dashboard/time-tracker'
    | '/dashboard/workout'
    | '/test/error'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/test/error': {
      id: '/test/error'
      path: '/test/error'
      fullPath: '/test/error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workout': {
      id: '/dashboard/workout'
      path: '/workout'
      fullPath: '/dashboard/workout'
      preLoaderRoute: typeof DashboardWorkoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/time-tracker': {
      id: '/dashboard/time-tracker'
      path: '/time-tracker'
      fullPath: '/dashboard/time-tracker'
      preLoaderRoute: typeof DashboardTimeTrackerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/site-blocking': {
      id: '/dashboard/site-blocking'
      path: '/site-blocking'
      fullPath: '/dashboard/site-blocking'
      preLoaderRoute: typeof DashboardSiteBlockingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSiteBlockingRoute: typeof DashboardSiteBlockingRoute
  DashboardTimeTrackerRoute: typeof DashboardTimeTrackerRoute
  DashboardWorkoutRoute: typeof DashboardWorkoutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSiteBlockingRoute: DashboardSiteBlockingRoute,
  DashboardTimeTrackerRoute: DashboardTimeTrackerRoute,
  DashboardWorkoutRoute: DashboardWorkoutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
